apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-resizable
spec:
  serviceName: "nginx-stateful-resizable"
  replicas: 2
  selector:
    matchLabels:
      app: nginx-stateful-resizable
  template:
    metadata:
      labels:
        app: nginx-stateful-resizable
    spec:
      containers:
      - name: nginx-stateful-resizable
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: web-resizable
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        # Prevent 403
      securityContext:
        fsGroup: 0
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2-resizable"
      resources:
        requests:
          storage: 1Gi
