apiVersion: v1
kind: Service
metadata:
  name: nginx-service-statefulset-unresizable-loadbalancer
  labels:
    app: nginx-stateful-unresizable
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: web-unresizable
  selector:
    app: nginx-stateful-unresizable
